Initial setup
C1C0/internal-team-skolska-stranka pull request #1
Opened 2023-02-17 06:06 UTC by C1C0

Takže chalani, prvý testovacie PR. Skúste sa na to pozrieť, a urobiť nasledovné:

- Pridať globálny komentár
- Pridať komentár na konkrétne riadky v kóde
- Využite aj "review" system v rámci githubu

2023-02-17 06:11 UTC, C1C0 reviewed
Toto je môj komentár po skontrolovaní súborov v PRku

2023-02-23 19:16 UTC, SamoSadlaker commented on .env.example
> +MYSQL_PASSWORD=secret
Zlý example súbor.. tu má byť iné heslo ktoré sa používa v kóde.
Buď zmeniť heslo tu, alebo php apku prinútiť používať .env súbor

2023-02-23 19:17 UTC, SamoSadlaker requested changes
Opraviť rozdielne heslá v .env súbore a v aplikácii

2023-02-23 19:18 UTC, SamoSadlaker commented
Globálny komentár 😃

2023-02-26 09:01 UTC, SamoSadlaker approved these changes

2023-02-26 09:02 UTC, merged